eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8889
spring:
  application:
    name: chen-zuul
zuul:
  routes:
    api-a:
      path: /api-member/**
      service-id: chen-member
    api-b:
      path: /api-order/**
      service-id: chen-order
